[package]
name = "deno-sodium"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.2.4"
napi-derive = "3.2.4"
libsodium-rs = "0.1.1"

[build-dependencies]
napi-build = "2.2.3"
